# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1dde64bc8d27a54a83704d6d13924dff39944d9d95d2d885de321e3b94e9b29c9b5f4a2e14c790d808a396e1d7a9e2cf5103632d95c34dac9a9c19675de6d53

test:
  secret_key_base: 785529d62406e2a09d785cf018f10067aad4ba3793b829ad182c36c6a127871382cd3f232032a79339eae6857e46ffc433733ce55c9df25b12bbe2a51b8ba5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
